---
- name: create directory and download tomcat package from tomcat.apache.org
  hosts: localhost

  tasks:
          - name: create directory
            file:
                    path: /home/hananmansour/Desktop/tomcat
                    state: directory
                    mode: 0755
                    owner: root


          - name : download tomcat package from url
            get_url:
                 url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
                 dest: /home/hananmansour/Desktop/tomcat


